#AC_PATTERN_REPLACEMENTS := | sed -e "s/std::.*basic_string<char.*>/<<<replaced>>>/" | sed -e "s/void /VOID  /"
AC_PATTERN_REPLACEMENTS := | sed -e "s/std::.*basic_string<char.*>/<<<replaced>>>/"
include ../Makefile.generic
